import type { Metadata } from "next";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import { lato } from "@/config/FontFamily";

export const metadata: Metadata = {
  title: "Veepearls",
  description: "Generated by create next app",
  icons: "./favicon.ico",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <Theme>
          <main className={lato.className}>{children}</main>
        </Theme>
      </body>
    </html>
  );
}
